// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Record</b><br>
 * Generated     : <b>2012/07/16 ÉÏÎç10:49:16</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows Server 2003 x86 5.2 build 3790 Service Pack 2 <br>
 * 
 * @since  7 16, 2012
 * @author qiaorg
 */
public abstract class RecordHelper extends RationalTestScript
{
	protected RecordHelper()
	{
		setScriptName("Record");
	}
}
